name: easy_onvif
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.
version: 0.0.6
repository: https://github.com/faithoflifedev/easy_onvif
homepage: https://github.com/faithoflifedev/easy_onvif

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  dio: ^4.0.0
  easy_enum: ^1.0.0
  json_annotation: ^4.0.1
  universal_io: ^2.0.4
  uuid: ^3.0.4
  xml: ^5.1.0
  xml2json: ^5.3.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.1
  easy_enum_generator: ^1.0.2
  grinder: ^0.9.0
  json_serializable: ^4.1.1
  mustache_template: ^2.0.0
  process_run: ^0.12.1
  test: ^1.17.5
