name: easy_onvif
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.
version: 1.0.0
repository: https://github.com/faithoflifedev/easy_onvif
homepage: https://github.com/faithoflifedev/easy_onvif

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  easy_enum: ^1.0.0
  xml: ^5.1.0
  json_annotation: ^4.0.1
  xml2json: ^5.1.0
  crypto: ^3.0.1
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.1
  easy_enum_generator: ^1.0.2
  json_serializable: ^4.1.1
