name: easy_onvif
description: A pure Dart library designed primarily for command line automation of Onvif compatible devices, but can be used anywhere Dart is used.
version: 2.0.5
repository: https://github.com/faithoflifedev/easy_onvif
homepage: https://github.com/faithoflifedev/easy_onvif

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  crypto: ^3.0.2
  dio: ^4.0.6
  intl: ^0.17.0
  json_annotation: ^4.5.0
  loggy: ^2.0.1+1
  # loggy:
  #   git:
  #     url: https://github.com/faithoflifedev/floggy.git
  #     ref: stderr_loggy
  #     path: loggy

  sprintf: ^6.0.0
  universal_io: ^2.0.4
  uuid: ^3.0.6
  xml: ^6.1.0
  xml2json: ^5.3.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  grinder: ^0.9.2
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mustache_template: ^2.0.0
  process_run: ^0.12.3+2
  test: ^1.21.0

executables:
  onvif:
