name: flutter_model
description: A new Flutter project to test Onvif.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  easy_onvif:
    path: ../../
  flutter_loggy: ^2.0.1
  # flutter_loggy:
  #   git:
  #     url: https://github.com/faithoflifedev/floggy.git
  #     ref: stderr_loggy
  #     path: flutter_loggy
  loggy: ^2.0.1+1
  # loggy:
  #   git:
  #     url: https://github.com/faithoflifedev/floggy.git
  #     ref: stderr_loggy
  #     path: loggy
  yaml: ^3.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - config.yaml
