name: flutter_model
description: A new Flutter project to test Onvif.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  easy_onvif:
    path: ../../
  yaml: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  xml: ^5.4.0
  collection: ^1.16.0

flutter:
  uses-material-design: true

  assets:
    - config.yaml
