templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 2.0.10
change: |
  * homebrew installation for onvif cli
  * default debug for cli now set to "off"
