repo: faithoflifedev/easy_onvif
templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 2.0.11
change: |
  * tweak to README
  * bool response for `gotoPreset`
  * auto create release during publish
