templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 0.0.13
change: The "GetSystemDateAndTimeResponse" now better matches the spec and a typo fix for the "GetCapabilities" request.
