repo: faithoflifedev/easy_onvif

pkg:
  githubBearerToken: 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
  humanName: easy_onvif
  botName: FLN Developer
  botEmail: faithoflifedev@gmail.com

  homebrewRepo: faithoflifedev/homebrew-easy_onvif

meta: lib/src/util/meta.dart

templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 2.0.13+2
commit: "improved build tools, moved model folder into src folder"
change: |
  * improved build tools
  * moved model folder into src folder
