templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 0.0.14
change: Added "GetConfiguration" and "GetConfigurations" the PTZ move helper functions move based on device defaults.
