repo: faithoflifedev/easy_onvif
templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 2.0.13+1
change: |
  * finally figured out why meta.dart wasn't updating correctly
