repo: faithoflifedev/easy_onvif

pkg:
  githubBearerToken: [access token]
  humanName: easy_onvif
  botName: FLN Developer
  botEmail: faithoflifedev@gmail.com
  executables:
    obs: bin/onvif.dart
  homebrewRepo: faithoflifedev/homebrew-easy_onvif
  # homebrewFormula: Formula/obs.rb

meta: lib/src/util/meta.dart

templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

commit: more config requests, tests and improved build tools
change: |
  * updated build tools
  * dependency bump
