templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 0.0.11
change: ONVIF SOAP faults do not match the spec they refer to on some devices, and now a static instance of Dio.
