templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 2.0.6
change: "improved logging and support for non-compliant TL-IPC43AN-4 with simulated RelativeMove and DateTime.tryParse"
